version: '3'
services:
  web:
    build: ./app
    ports:
      - "8888:8888"
    env_file:
      - .env
    environment:
      - RMQ_LOGIN=${RMQ_LOGIN:-guest}
      - RMQ_PASSWORD=${RMQ_PASSWORD:-guest}
      - RMQ_HOST=${RMQ_HOST:-rabbitmq}
      - RMQ_PORT=${RMQ_PORT:-5672}
    depends_on:
      - rabbitmq
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-guest}
